version: '3'
services:
  node:
    ports: 
      - "3600:3600"
    volumes: 
      - ..:/workspace
      - .zshrc:/home/node/.zshrc
      - .zshrc:/root/.zshrc
    build: 
      context: .
      dockerfile: Dockerfile
    command: sleep infinity