version: '3.7'

services:

  dotnet:
    image: ghcr.io/mdhthahmd/devcontainers/dotnet:sdk-3.1.412-nodejs-14.17.6  
    volumes:
      - ..:/workspace
    user: vscode
    command: sleep infinity

   