name: Build, publish and version dotnet devcontainer image

on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/dotnet

jobs:
  publish-latest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Extract metadata (tags, labels) for docker
        id: meta
        uses: docker/metadata-action@v3.5.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
          labels: |
            maintainer=${{ github.actor }}
            org.opencontainers.image.title=dotnet 5.0 devcontainer
            org.opencontainers.image.description=A devlopment environment for dotnet applications, nvm and nodejs is intalled
            org.opencontainers.image.vendor=${{ github.actor }}

      - name: Build and push docker image
        uses: docker/build-push-action@v2.7.0
        with:
          context: ./containers/dotnet
          build-args: |
            VARIANT=5.0
            NODE_VERSION=lts/*
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  
  generate-tag:
    needs: publish-latest
    runs-on: ubuntu-latest
    container: 
      image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}

    steps: 
      - name: See the tag from current version numbers
        run: echo "sdk-$(dotnet --version)-nodejs-$(echo $(node --version) | cut -c 2-)"

      - name: Retrieve Tag
        run: |
          echo "::set-output name=tag::$(echo "sdk-$(dotnet --version)-nodejs-$(echo $(node --version) | cut -c 2-)")"
          
    outputs:
      tag: ${{ steps.version.outputs.tag }}
  
  apply-tag:
    needs: generate-tag
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Log in to the container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Pull the latest image
        run: docker pull ghcr.io/mdhthahmd/devcontainers/dotnet:latest

      - name: Re-Tag the latest image with versioned tag
        run: docker tag ghcr.io/mdhthahmd/devcontainers/dotnet:latest ghcr.io/mdhthahmd/devcontainers/dotnet:${{ needs.generate-tag.outputs.tag }}

      - name: Push the image to registry
        run: docker push ghcr.io/mdhthahmd/devcontainers/dotnet:${{ needs.generate-tag.outputs.tag }}
      
