name: Update the .environments File

on:
  push:
    paths:
      - 'config'
      - '.github/workflows/environments.yml'
      - '.environments'

jobs:
  update-env-list:
    name: Update .environments File
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Write to .environments File
        run: |
          cat /dev/null > .environments
          cd config
          ls -1d -- */ | sed 's/\///g' >> ../.environments

      - name: Set up git
        run : |
          git remote set-url origin https://github.com/mdhthahmd/devcontainers.git
          git config --local user.email "mdhthahmd@gmail.com"
          git config --local user.name "mdhthahmd"
          git commit -m "updated .environnemnts file" -a
          git push "https://mdhthahmd:${{ secrets.GH_TOKEN }}@github.com/mdhthahmd/devcontainers.git $GITHUB_REF"
