name: Update the .environments File

on:
  push:
    paths:
      - 'config/**'
      - '.github/workflows/environments.yml'
      - '.environments'
  
  workflow_dispatch:

jobs:
  update-env-list:
    name: Update .environments File
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up git
        run : |
          git config --local user.email "mdhthahmd@gmail.com"
          git config --local user.name "mdhthahmd"

      - name : Delete .environments File
        run : |
          rm -rf .environments

      - name : Commit delete
        run : |
          git commit -m "deleted .envronments - ${{ github.event.head_commit.message }}" -a
          git push https://${{ secrets.GH_TOKEN }}@github.com/mdhthahmd/devcontainers.git

      - name: Update .environments File
        run: |
          cd config
          ls -1d -- */ | sed 's/\///g' > ../.environments
          cd ..

      - name: Commit update
        run: |
          git add .environments
          git commit -m "updated .envronments - ${{ github.event.head_commit.message }}"
          git push https://${{ secrets.GH_TOKEN }}@github.com/mdhthahmd/devcontainers.git

