name: Update the .environments File

on:
  push:
    paths:
      - 'config'
      - '.github/workflows/environments.yml'
      - '.environments'

jobs:
  update-env-list:
    name: Update .environments File
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Write to .environments File
        run: |
          cat /dev/null > .environments
          cd config
          ls -1d -- */ | sed 's/\///g' >> ../.environments

      - name: Set up git
        run : |
          git config --local user.email "mdhthahmd@gmail.com"
          git config --local user.name "mdhthahmd"
          git commit -m "updated .environnemnts file" -a
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: ${{ github.ref }}
