name: Add versioned tags for the latest image

on:
  workflow_run:
    workflows: ["Create and publish dotnet devcontainer image"]
    types:
      - completed

env:
  REGISTRY: ghcr.io

jobs:
  generate-tag:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/mdhthahmd/devcontainers/dotnet:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}

    steps: 
      - name: See the tag from current version numbers
        run: echo "sdk-$(dotnet --version)-nodejs-$(echo $(node --version) | cut -c 2-)"

      - name: Retrieve Tag
        id: version
        run: |
          echo "::set-output name=tag::$(echo "sdk-$(dotnet --version)-nodejs-$(echo $(node --version) | cut -c 2-)")"
          
    outputs:
      tag: ${{ steps.version.outputs.tag }}
  
  apply-tag:
    needs: generate-tag
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Log in to the container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Pull the latest image
        run: docker pull ghcr.io/mdhthahmd/devcontainers/dotnet:latest

      - name: Re-Tag the latest image with versioned tag
        run: docker tag ghcr.io/mdhthahmd/devcontainers/dotnet:latest ghcr.io/mdhthahmd/devcontainers/dotnet:${{ needs.generate-tag.outputs.tag }}

      - name: Push the image to registry
        run: docker push ghcr.io/mdhthahmd/devcontainers/dotnet:${{ needs.generate-tag.outputs.tag }}
